# Generated by Django 2.1.1 on 2018-10-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='original_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
