# Generated by Django 2.1.1 on 2018-11-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0002_asset_original_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='assets',
        ),
        migrations.AddField(
            model_name='asset',
            name='locations',
            field=models.ManyToManyField(through='assetmanager.Count', to='assetmanager.Location'),
        ),
    ]
