# Generated by Django 2.1.1 on 2019-04-17 00:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0002_auto_20190417_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('manager', 'Manager')], max_length=7, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
