# Generated by Django 2.1.1 on 2019-04-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0003_auto_20190417_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extendeduser',
            options={'permissions': (('create_manager', 'Can create a user that is a manager.'), ('create_regular_user', 'Can create a regular user.'))},
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('manager', 'Manager')], max_length=7),
        ),
    ]
