# Generated by Django 2.1.1 on 2018-11-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0004_auto_20181113_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
