# Generated by Django 2.1.1 on 2018-12-03 03:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0006_location_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
