# Generated by Django 2.1.1 on 2019-03-26 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0007_asset_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='in_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assetmanager.Location'),
        ),
    ]
