# Generated by Django 2.1.1 on 2019-04-07 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0009_auto_20190326_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assetmanager.Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('description', 'in_location')},
        ),
    ]
