# Generated by Django 2.1.1 on 2019-04-07 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0010_auto_20190408_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='in_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='assetmanager.Location'),
        ),
    ]
