# Generated by Django 2.1.1 on 2019-04-11 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetmanager', '0013_auto_20190408_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='in_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='assetmanager.Location'),
        ),
    ]
